# -*- coding: utf-8 -*-
"""delivery_idea.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MIW3rI5XokT_mbvbhcymBykGautWuHI8

# 국내여행이 트렌드가 되고 있다 ?
- 포스트코로나 현황하에 지속성 있는 유망산업인가?
- 비대면 레져 및 오락
  - 레져 매출은 전년대비 줄었으나 그 중 세부종목 중 오른것 발굴(예 : 골프)
- 캠핑 등의 예능방송 증가추세(바퀴달린집)
- 

## 활동산업동향
- [2020년 5월 산업활동동향](http://kostat.go.kr/portal/korea/kor_nw/1/1/index.board?bmode=read&aSeq=383475)
  -  숙박업 매출이 전년동월대비 감소하였으나 전월대비 증가추세임(3월~)

## 1/4 분기 온라인 소비 동향
- [온라인 소비 동향 등](http://kostat.go.kr/portal/korea/kor_nw/3/index.board)
  - 검색어 : 온라인 등으로 검색
- 

## 1/4 분기 가계소비동향 조사
- [(1인) 가구 가계 소비 동향 조사 (통계청)](http://kostat.go.kr/portal/korea/kor_nw/1/4/3/index.board?bmode=read&bSeq=&aSeq=382592&pageNo=1&rowNum=10&navCount=10&currPg=&searchInfo=&sTarget=title&sTxt=)

## 관광지 이용객 추이 조사
- [시도별 국내관광여행횟수](http://kosis.kr/statisticsList/statisticsListIndex.do?menuId=M_01_03_01&vwcd=MT_GTITLE01&parmTabId=M_01_03_01)
- [경남주요관광지점 입장객수](https://know.tour.go.kr/stat/visitStatDis/table.do)
- [5월 해외관광 출입객수](https://kto.visitkorea.or.kr/kor/notice/data/statis/profit/board/view.kto?id=441838&isNotice=false&instanceId=294&rnum=1)

## 각종 지수 
- [인기 지표모음. 추후 필요한것 가져오기](http://www.index.go.kr/potal/main/EachPage.do?mmenu=7&smenu=2)
"""



